/**
 * eSIM Installation Utilities
 * 
 * Handles eSIM profile installation flows for mobile devices.
 * Implements GSMA SGP.22 LPA (Local Profile Assistant) URL format.
 * 
 * GSMA Standard Format:
 * LPA:1$<SM-DP+ server>$<activation code>
 * 
 * Platform-specific deep links:
 * - iOS: https://esimsetup.apple.com/esim_qrcode_provisioning?carddata=<LPA_URL>
 * - Android: https://esimsetup.android.com/esim_qrcode_provisioning?carddata=<LPA_URL>
 * 
 * @see RESEARCH-UX-FIXES.md for GSMA standards and implementation details
 * @see https://www.gsma.com/esim/esim-specification/ for official spec
 */

import { isIOS, isAndroid } from './deviceDetection';

/**
 * ⚠️ BLOCKED: eSIM Provider Integration Required
 * 
 * This implementation provides the correct structure and standards compliance,
 * but requires actual eSIM provider integration to function.
 * 
 * REQUIRED FROM PROVIDER:
 * 1. SM-DP+ server address (e.g., 'rsp.truphone.com', 'lpa.esim.live')
 * 2. API endpoint to generate activation codes
 * 3. Order ID → Activation Code mapping
 * 
 * INTEGRATION OPTIONS:
 * - Truphone: https://www.truphone.com/esim/
 * - Telnyx: https://telnyx.com/products/esim
 * - eSIM Go: https://www.esim-go.com/
 * - 1GLOBAL Connect: https://www.1global.com/
 * 
 * Current implementation uses placeholder structure only.
 */

export interface ESIMActivation {
  orderId: string;
  smdpAddress: string;      // SM-DP+ server address
  activationCode: string;   // Provider-issued activation code
  matchingId?: string;      // Optional matching ID (provider-specific)
}

/**
 * Generate LPA (Local Profile Assistant) URL for eSIM installation.
 * 
 * Format: LPA:1$<SM-DP+ server>$<activation code>[$<matchingId>]
 * 
 * @param activation - eSIM activation details from provider
 * @returns {string} GSMA-compliant LPA URL
 * 
 * @example
 * ```typescript
 * const lpaUrl = generateLPAUrl({
 *   orderId: 'ORD-12345',
 *   smdpAddress: 'rsp.truphone.com',
 *   activationCode: 'ABC123XYZ789'
 * });
 * // Returns: "LPA:1$rsp.truphone.com$ABC123XYZ789"
 * ```
 */
export function generateLPAUrl(activation: ESIMActivation): string {
  const { smdpAddress, activationCode, matchingId } = activation;
  
  // GSMA SGP.22 standard format
  let lpaUrl = `LPA:1$${smdpAddress}$${activationCode}`;
  
  // Optional matching ID (some providers require this)
  if (matchingId) {
    lpaUrl += `$${matchingId}`;
  }
  
  return lpaUrl;
}

/**
 * Generate platform-specific installation URL.
 * 
 * Creates deep links that open the device's native eSIM settings
 * with the activation profile pre-loaded.
 * 
 * iOS: Opens Settings → Cellular → Add eSIM
 * Android: Opens eSIM Manager with activation profile
 * 
 * @param lpaUrl - GSMA-compliant LPA URL
 * @returns {string} Platform-specific deep link URL
 * 
 * @example
 * ```typescript
 * const lpaUrl = generateLPAUrl(activation);
 * const installUrl = generateInstallUrl(lpaUrl);
 * // iOS: https://esimsetup.apple.com/esim_qrcode_provisioning?carddata=LPA:1$...
 * // Android: https://esimsetup.android.com/esim_qrcode_provisioning?carddata=LPA:1$...
 * ```
 */
export function generateInstallUrl(lpaUrl: string): string {
  // URL-encode the LPA string for safe transmission
  const encodedLPA = encodeURIComponent(lpaUrl);
  
  if (isIOS()) {
    // iOS universal link (iOS 12.1+)
    return `https://esimsetup.apple.com/esim_qrcode_provisioning?carddata=${encodedLPA}`;
  }
  
  if (isAndroid()) {
    // Android universal link (Android 9+)
    return `https://esimsetup.android.com/esim_qrcode_provisioning?carddata=${encodedLPA}`;
  }
  
  // Fallback: Return raw LPA URL (for QR code generation)
  return lpaUrl;
}

/**
 * ⚠️ PLACEHOLDER IMPLEMENTATION
 * 
 * Fetch eSIM activation details for an order.
 * 
 * THIS REQUIRES BACKEND INTEGRATION:
 * 
 * ```typescript
 * // Backend endpoint needed:
 * GET /api/esim-activation/{orderId}
 * 
 * // Response format:
 * {
 *   orderId: string;
 *   smdpAddress: string;      // From provider config
 *   activationCode: string;   // Generated by provider API
 *   matchingId?: string;      // Optional
 * }
 * ```
 * 
 * PROVIDER API INTEGRATION PATTERN:
 * 
 * ```typescript
 * // Server-side (after successful payment):
 * const activation = await esimProvider.createActivation({
 *   plan: selectedPlan,
 *   customer: { email, name }
 * });
 * 
 * // Store activation details with order:
 * await db.orders.update(orderId, {
 *   esimActivation: {
 *     smdpAddress: activation.smdpAddress,
 *     activationCode: activation.activationCode,
 *     matchingId: activation.matchingId
 *   }
 * });
 * ```
 * 
 * @param orderId - Order ID to fetch activation for
 * @returns {Promise<ESIMActivation>} eSIM activation details
 */
export async function fetchActivationDetails(orderId: string): Promise<ESIMActivation> {
  // TODO: Replace with actual API call to backend
  // Backend should fetch from eSIM provider and return activation details
  
  console.warn(
    '⚠️ ESIM ACTIVATION BLOCKED: Provider integration required',
    '\nThis is a placeholder implementation.',
    '\nSee src/utils/esimInstallation.ts for integration requirements.'
  );
  
  // Placeholder response structure (for development/testing)
  return {
    orderId,
    smdpAddress: 'PLACEHOLDER.esim-provider.com', // ← Replace with actual provider
    activationCode: 'PLACEHOLDER_CODE',            // ← From provider API
    matchingId: undefined
  };
}

/**
 * Generate QR code data URL for desktop users.
 * 
 * Desktop users need to scan the QR code with their mobile device
 * to install the eSIM profile.
 * 
 * @param lpaUrl - GSMA-compliant LPA URL
 * @returns {Promise<string>} Data URL for QR code image
 * 
 * Note: This requires a QR code generation library.
 * Recommended: qrcode (npm package)
 * 
 * ```bash
 * npm install qrcode @types/qrcode
 * ```
 * 
 * Implementation:
 * ```typescript
 * import QRCode from 'qrcode';
 * 
 * export async function generateQRCodeDataUrl(lpaUrl: string): Promise<string> {
 *   return await QRCode.toDataURL(lpaUrl, {
 *     width: 256,
 *     margin: 2,
 *     color: {
 *       dark: '#000000',
 *       light: '#FFFFFF'
 *     }
 *   });
 * }
 * ```
 */
export async function generateQRCodeDataUrl(_lpaUrl: string): Promise<string> {
  // TODO: Implement with qrcode library
  // For now, return placeholder
  console.warn('QR code generation not implemented. Install "qrcode" package.');
  // Placeholder SVG (will be replaced with actual QR code after qrcode package installed)
  return `data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><rect width="200" height="200" fill="%23f0f0f0"/><text x="50%" y="50%" text-anchor="middle" dy=".3em" fill="%23999">QR Code</text></svg>`;
}
